### PR TITLE
Dealing with non-picklable objects

### PR DESCRIPTION
**Pull request by neelasha23**
The PR tries to solve https://github.com/ploomber/soorgeon/issues/9
1. Added a CLI option called serializer which can be one of cloudpickle or dill
2. Based on the serializer selected soorgeon will try to pickle the objects with either cloudpickle or dill
3. Both the packages are optional dependencies

### CODE REVIEW

**Comment by neelasha23** [comment]
1. 3 testcases in test_export.py  are failing on the main branch . Does this need a fix?

```FAILED tests/test_export.py::test_prototask_un_pickling_cells[none] - AssertionError: assert 'Path(product...kle.dumps(x))' == 'Path(product...kle.dumps(x))'
FAILED tests/test_export.py::test_prototask_un_pickling_cells[parquet] - AssertionError: assert 'Path(product...kle.dumps(x))' == 'Path(product...kle.dumps(x))'
FAILED tests/test_export.py::test_prototask_un_pickling_cells[csv] - AssertionError: assert 'Path(product...kle.dumps(x))' == 'Path(product...kle.dumps(x))'
============================================================================= 3 failed, 41 passed, 11 warnings in 30.61s =====================================```

2. I tried to include a test case similar to https://github.com/ploomber/soorgeon/blob/dc2d77603ee21800c46aa16ca19684aa97004e79/tests/test_export.py#L226
with a non-picklable function, parametrized by the serializers. However it obviously fails because cloudpickle or dill are not installed. Any suggestions on how to go about this?

**Comment by idomic** [comment]
@neelasha23 I see that the mainline is green from last push, I think it's something that's coming from the code change

**Comment by neelasha23** [comment]
Which mainline? I didn't get it

**Comment by neelasha23** [comment]
You mean this : https://github.com/ploomber/soorgeon/actions/runs/2375136937 ?

**Comment by neelasha23** [comment]
Okay, got it. I think it was referring to an incorrect build in my local, so I thought it's coming from main. I'll look into this

**Pull request merged**
